Algoritmo "exercio_66_1a_manzano"
// Disciplina : Lógica de Programação
// Professor : Jaison Costa
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2025
Var
   // Seção de Declarações das variáveis
var i: inteiro
inicio
   para i de 15 ate 200 faca
      escreval(i, "^2 = ", i * i)
   fimpara
Fimalgoritmo