Algoritmo "exercio_46_5a_manzano"
// Disciplina : Lógica de Programação
// Professor : Jaison Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2025
Var
   // Seção de Declarações das variáveis
   n, i: inteiro
inicio
   escreval("Digite um número para ver a tabuada: ")
   leia(n)

   para i de 1 ate 10 faca
      escreval(n, " x ", i, " = ", n * i)
   fimpara


Fimalgoritmo