Algoritmo "exercio_66_1e_manzano"
// Disciplina : Lógica de Programação
// Professor : Jaison Costa
// Descrição   : Apresentar todos os valores numéricos inteiros ímpares situados na faixa de 0 a 20.
// Autor(a)    : Eduarda Coelho
// Data atual  : 25/09/2025
Var
   // Seção de Declarações das variáveis
   i: inteiro
inicio
   para i de 0 ate 20 faca
      se i % 2 <> 0 entao
         escreval(i)
      fimse
   fimpara

Fimalgoritmo
